import type { ModelInfo } from './types';

const MB = 1024 * 1024;

export const MODEL_REGISTRY: ModelInfo[] = [
	{
		id: 'sam2.1-tiny',
		name: 'SAM 2.1 Tiny',
		family: 'sam2.1',
		variant: 'tiny',
		encoderSize: 129 * MB,
		decoderSize: 16 * MB,
		totalSize: 145 * MB,
		description: 'Fastest SAM 2.1, pre-optimized encoder',
		encoderKey: 'models/sam2.1-tiny/v1/encoder.ort',
		decoderKey: 'models/sam2.1-tiny/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'sam2.1-small',
		name: 'SAM 2.1 Small',
		family: 'sam2.1',
		variant: 'small',
		encoderSize: 156 * MB,
		decoderSize: 16 * MB,
		totalSize: 172 * MB,
		description: 'Balanced speed and accuracy for SAM 2.1',
		encoderKey: 'models/sam2.1-small/v1/encoder.ort',
		decoderKey: 'models/sam2.1-small/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'sam2.1-baseplus',
		name: 'SAM 2.1 Base+',
		family: 'sam2.1',
		variant: 'base+',
		encoderSize: 324 * MB,
		decoderSize: 16 * MB,
		totalSize: 340 * MB,
		description: 'Higher accuracy SAM 2.1 model',
		encoderKey: 'models/sam2.1-baseplus/v1/encoder.ort',
		decoderKey: 'models/sam2.1-baseplus/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'sam2.1-large',
		name: 'SAM 2.1 Large',
		family: 'sam2.1',
		variant: 'large',
		encoderSize: 862 * MB,
		decoderSize: 16 * MB,
		totalSize: 878 * MB,
		description: 'Highest accuracy SAM 2.1, large download',
		encoderKey: 'models/sam2.1-large/v1/encoder.ort',
		decoderKey: 'models/sam2.1-large/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'sam2-tiny',
		name: 'SAM 2 Tiny',
		family: 'sam2',
		variant: 'tiny',
		encoderSize: 128 * MB,
		decoderSize: 20 * MB,
		totalSize: 148 * MB,
		description: 'Fastest SAM 2 model (prefer SAM 2.1 for better accuracy)',
		encoderKey: 'models/sam2-tiny/v1/encoder.ort',
		decoderKey: 'models/sam2-tiny/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'sam2-small',
		name: 'SAM 2 Small',
		family: 'sam2',
		variant: 'small',
		encoderSize: 155 * MB,
		decoderSize: 20 * MB,
		totalSize: 175 * MB,
		description: 'Balanced SAM 2 model',
		encoderKey: 'models/sam2-small/v1/encoder.ort',
		decoderKey: 'models/sam2-small/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'sam2-baseplus',
		name: 'SAM 2 Base+',
		family: 'sam2',
		variant: 'base+',
		encoderSize: 324 * MB,
		decoderSize: 20 * MB,
		totalSize: 344 * MB,
		description: 'Higher accuracy SAM 2 model',
		encoderKey: 'models/sam2-baseplus/v1/encoder.ort',
		decoderKey: 'models/sam2-baseplus/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'sam2-large',
		name: 'SAM 2 Large',
		family: 'sam2',
		variant: 'large',
		encoderSize: 849 * MB,
		decoderSize: 20 * MB,
		totalSize: 869 * MB,
		description: 'Highest accuracy SAM 2, large download',
		encoderKey: 'models/sam2-large/v1/encoder.ort',
		decoderKey: 'models/sam2-large/v1/decoder.onnx',
		quantization: 'fp32',
		requiresWebGPU: true,
	},
	{
		id: 'slimsam-77',
		name: 'SlimSAM-77',
		family: 'sam1',
		variant: 'slimsam-77',
		encoderSize: 9 * MB,
		decoderSize: 5 * MB,
		totalSize: 14 * MB,
		description: 'Recommended CPU-only model, 77% pruned SAM (~14 MB INT8)',
		encoderKey: 'models/slimsam-77/v1/encoder.onnx',
		decoderKey: 'models/slimsam-77/v1/decoder.onnx',
		quantization: 'int8',
		requiresWebGPU: false,
	},
];

export const MODEL_FAMILIES = [
	{ id: 'sam2.1' as const, label: 'SAM 2.1' },
	{ id: 'sam2' as const, label: 'SAM 2' },
	{ id: 'sam1' as const, label: 'SAM 1 / Lightweight' },
];

export function formatBytes(bytes: number): string {
	if (bytes < 1024) return `${bytes} B`;
	if (bytes < MB) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / MB).toFixed(0)} MB`;
}
