import type { ModelInfo } from './types';

const MB = 1024 * 1024;

export const MODEL_REGISTRY: ModelInfo[] = [
	{
		id: 'sam2.1-tiny',
		name: 'SAM 2.1 Tiny',
		family: 'sam2.1',
		variant: 'tiny',
		encoderSize: 35 * MB,
		decoderSize: 4 * MB,
		totalSize: 39 * MB,
		description: 'Fastest SAM 2.1 model, good for real-time use',
		encoderUrl: 'https://example.com/sam2.1-tiny-encoder.onnx',
		decoderUrl: 'https://example.com/sam2.1-tiny-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: false,
	},
	{
		id: 'sam2.1-small',
		name: 'SAM 2.1 Small',
		family: 'sam2.1',
		variant: 'small',
		encoderSize: 41 * MB,
		decoderSize: 5 * MB,
		totalSize: 46 * MB,
		description: 'Balanced speed and accuracy for SAM 2.1',
		encoderUrl: 'https://example.com/sam2.1-small-encoder.onnx',
		decoderUrl: 'https://example.com/sam2.1-small-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: false,
	},
	{
		id: 'sam2.1-baseplus',
		name: 'SAM 2.1 Base+',
		family: 'sam2.1',
		variant: 'base+',
		encoderSize: 73 * MB,
		decoderSize: 8 * MB,
		totalSize: 81 * MB,
		description: 'Higher accuracy SAM 2.1 model',
		encoderUrl: 'https://example.com/sam2.1-baseplus-encoder.onnx',
		decoderUrl: 'https://example.com/sam2.1-baseplus-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: false,
	},
	{
		id: 'sam2.1-large',
		name: 'SAM 2.1 Large',
		family: 'sam2.1',
		variant: 'large',
		encoderSize: 210 * MB,
		decoderSize: 15 * MB,
		totalSize: 225 * MB,
		description: 'Highest accuracy SAM 2.1, requires more memory',
		encoderUrl: 'https://example.com/sam2.1-large-encoder.onnx',
		decoderUrl: 'https://example.com/sam2.1-large-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: true,
	},
	{
		id: 'sam2-tiny',
		name: 'SAM 2 Tiny',
		family: 'sam2',
		variant: 'tiny',
		encoderSize: 35 * MB,
		decoderSize: 4 * MB,
		totalSize: 39 * MB,
		description: 'Fastest SAM 2 model',
		encoderUrl: 'https://example.com/sam2-tiny-encoder.onnx',
		decoderUrl: 'https://example.com/sam2-tiny-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: false,
	},
	{
		id: 'sam2-small',
		name: 'SAM 2 Small',
		family: 'sam2',
		variant: 'small',
		encoderSize: 41 * MB,
		decoderSize: 5 * MB,
		totalSize: 46 * MB,
		description: 'Balanced SAM 2 model',
		encoderUrl: 'https://example.com/sam2-small-encoder.onnx',
		decoderUrl: 'https://example.com/sam2-small-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: false,
	},
	{
		id: 'sam2-baseplus',
		name: 'SAM 2 Base+',
		family: 'sam2',
		variant: 'base+',
		encoderSize: 73 * MB,
		decoderSize: 8 * MB,
		totalSize: 81 * MB,
		description: 'Higher accuracy SAM 2 model',
		encoderUrl: 'https://example.com/sam2-baseplus-encoder.onnx',
		decoderUrl: 'https://example.com/sam2-baseplus-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: false,
	},
	{
		id: 'sam2-large',
		name: 'SAM 2 Large',
		family: 'sam2',
		variant: 'large',
		encoderSize: 210 * MB,
		decoderSize: 15 * MB,
		totalSize: 225 * MB,
		description: 'Highest accuracy SAM 2, requires more memory',
		encoderUrl: 'https://example.com/sam2-large-encoder.onnx',
		decoderUrl: 'https://example.com/sam2-large-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: true,
	},
	{
		id: 'mobilesam',
		name: 'MobileSAM',
		family: 'mobile',
		variant: 'mobile',
		encoderSize: 9 * MB,
		decoderSize: 1 * MB,
		totalSize: 10 * MB,
		description: 'Lightweight model optimized for mobile and edge devices',
		encoderUrl: 'https://example.com/mobilesam-encoder.onnx',
		decoderUrl: 'https://example.com/mobilesam-decoder.onnx',
		quantization: 'int8',
		requiresWebGPU: false,
	},
	{
		id: 'efficientsam-s',
		name: 'EfficientSAM-S',
		family: 'mobile',
		variant: 'efficient-s',
		encoderSize: 22 * MB,
		decoderSize: 3 * MB,
		totalSize: 25 * MB,
		description: 'Efficient variant with good accuracy-speed tradeoff',
		encoderUrl: 'https://example.com/efficientsam-s-encoder.onnx',
		decoderUrl: 'https://example.com/efficientsam-s-decoder.onnx',
		quantization: 'fp16',
		requiresWebGPU: false,
	},
];

export const MODEL_FAMILIES = [
	{ id: 'sam2.1' as const, label: 'SAM 2.1' },
	{ id: 'sam2' as const, label: 'SAM 2' },
	{ id: 'mobile' as const, label: 'SAM 1 / Mobile' },
];

export function formatBytes(bytes: number): string {
	if (bytes < 1024) return `${bytes} B`;
	if (bytes < MB) return `${(bytes / 1024).toFixed(1)} KB`;
	return `${(bytes / MB).toFixed(0)} MB`;
}
